version: "3.9"

services:
  cassandra:
    image: cassandra:4
    ports:
      - 7000:7000
      - 9042:9042
  
  couchbase:
    image: couchbase
    ports:
     - 8091-8094:8091-8094
     - 11210:11210

  mongo:
    image: mongo:6
    ports:
      - 27017:27017
